export enum BrandExceptionCode {
   BRAND_NAME_REQUIRED = 'BRAND_NAME_REQUIRED',
   BRAND_NAME_LENGTH_INVALID = 'BRAND_NAME_LENGTH_INVALID',
   BRAND_DESCRIPTION_LENGTH_INVALID = 'BRAND_DESCRIPTION_LENGTH_INVALID',
   BRAND_NOT_FOUND = 'BRAND_NOT_FOUND',
}
