export enum CategoryExceptionCode {
   CATEGORY_NAME_REQUIRED = 'CATEGORY_NAME_REQUIRED',
   CATEGORY_NAME_LENGTH_INVALID = 'CATEGORY_NAME_LENGTH_INVALID',
   CATEGORY_DESCRIPTION_LENGTH_INVALID = 'CATEGORY_DESCRIPTION_LENGTH_INVALID',
   CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
}
