export enum DomainExceptionCode {
   DEFAULT_DOMAIN_EXCEPTION = 'DEFAULT_DOMAIN_EXCEPTION',
   UUID_INVALID = 'UUID_INVALID',
   INVALID_REQUIRED_STRING_MAX_LENGTH =  'INVALID_REQUIRED_STRING_MAX_LENGTH',
   INVALID_OPTIONAL_STRING_MAX_LENGTH =  'INVALID_OPTINAL_STRING_MAX_LENGTH',
   INVALID_REQUIRED_DATE =  'INVALID_REQUIRED_DATE',
   INVALID_NUMBER = 'INVALID_NUMBER',
   INVALID_BOOLEAN = 'INVALID_BOOLEAN',
   INVALID_ARGUMENT = 'INVALID_ARGUMENT'
}
